### ISSUE TITLE
create the basic ReadMe 

### ISSUE THREAD

**Issue by Zerocreative0815** [Cryxnoob/TeamProjectTH-BingenEP-1#1]
- create a README.md describing the project and listing your names (they do not have to be real names if you don’t want; GitHub user names are fine as well)

**Comment by nipafx** [comment]
Each of the four bullets should be a separate issue. I assume you've put them into one because they all touch on the README. But issues should be created, so that they are complete but small. As it stands, you'd have to do four mostly unrelated tasks to complete this one issue.

:bulb: The issue title is German - you can change that with the _Edit_ to the right of the title.

:bulb: If you leave a space after the dash `-`, GitHub will render the text as a proper list. You can change that with the pen icon on the top right corner of your comment.

**Comment by nipafx** [comment]
:+1:
