### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by Zerocreative0815** [Cryxnoob/TeamProjectTH-BingenEP-1#19]
- integrate with Travis (Mr.Parlock do that - ping him on the issue when Maven is set up)

**Comment by Zerocreative0815** [comment]
@nicolaiparlog

**Comment by nipafx** [comment]
Pardon my German:

Da dieses Projekt nicht zu einer Organisation gehört, sondern einem User, kann nur der User Travis aktivieren. 😭 Ich kann das nachher konfigurieren, aber anschmeißen muss es @Cryxnoob.

Dazu bitte Schritte 2 und 3 [aus dieser Anleitung](https://docs.travis-ci.com/user/for-beginners) (natürlich für dieses Projekt hier) durchführen und dann wieder hier Bescheid sagen.

(I've accidentally made this comment on the wrong issue at first and removed it since.)

**Comment by Cryxnoob** [comment]
Done (...I hope... ;) )

Am 2017-08-09 09:30, schrieb Nicolai Parlog:
